version: '3'
services:
  app:
    image: ${APP_IMAGE}
    volumes:
      - /root/logs/app:/usr/src/w-board/log
    environment:
      - RAILS_ENV
      - DATABASE_URL
      - WAKATIME_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    depends_on:
      - db
  web:
    image: nginx:1.17.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/secrets:/usr/secrets
      - /root/logs/web:/var/log/nginx
      - /root/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  db:
    image: ${DB_IMAGE}
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
