version: 2.1

workflows:
  main:
    jobs:
      - ruby-test

commands:
  prepare_env:
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run: gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}


jobs:
  ruby-test:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.2

      - image: circleci/mysql:8.0.16
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: w_board_test

    working_directory: ~/repo/server

    steps:
      - prepare_env
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: bin/rails db:create
      - run: bin/rails db:migrate
      - run: git diff --exit-code
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            export SPEC="./spec/**/*_spec.rb"
            export SPEC_OPTS="--tag ~external_api --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress"
            bin/rake spec

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
