# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
ruby '2.7.1'

gem 'httpclient'
gem 'aws-sdk-s3'
gem 'twitter'

group :development do
  gem 'solargraph'
end
