# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'httpclient'
gem 'aws-sdk-s3'

group :development do
  gem 'solargraph'
end
