version: '3'
services:
  app:
    image: ${APP_IMAGE}
    volumes:
      - /root/logs/app:/usr/src/w-board/log
    environment:
      - RAILS_ENV
      - DATABASE_URL
    depends_on:
      - db
  web:
    image: ${WEB_IMAGE}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/secrets:/usr/secrets
      - /root/logs/web:/var/log/nginx
    depends_on:
      - app
  db:
    image: ${DB_IMAGE}
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
